name: flutter_moor_tutorial
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_material_color_picker: ^1.0.5
  cupertino_icons: ^0.1.3
  moor_flutter: ^1.6.0

  # For the UI
  provider: ^3.0.0+1
  flutter_slidable: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^1.6.0
  build_runner:

flutter:
  uses-material-design: true
